name: PUBLISH_TO_gh
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: Build
        run: hugo
      # - name: CNAME
      #   run: echo "xxx" > CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
